version: '3'
services:
  cloud_server:
    build: .
    command: bash -c "echo DIESEL && steve"
    working_dir: /steve
    volumes:
      - ./builds:/steve/target
      - ./migrations:/steve/migrations
      - ./diesel.toml:/steve/diesel.toml
      - ./Cargo.toml:/steve/Cargo.toml
      - ./Cargo.lock:/steve/Cargo.lock
    depends_on:
      - db
    links:
      - db
    environment:
      - PREFIX=${PREFIX}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RSPOTIFY_CLIENT_ID=${RSPOTIFY_CLIENT_ID}
      - RSPOTIFY_CLIENT_SECRET=${RSPOTIFY_CLIENT_SECRET}
      - RSPOTIFY_REDIRECT_URI=${RSPOTIFY_REDIRECT_URI}
  db:
    image: "mariadb:latest"
    restart: always
    command: --port 5432
    volumes:
      - /home/ryan/Documents/stevedb:/var/lib/mysql
    ports:
      - "5432:5432"
    environment:
      # - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
volumes:
  db: