name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: sudo apt-get install build-essential default-libmysqlclient-dev autoconf automake libtool m4 libopus-dev  -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
